// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `product.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.mycat.eshop.intf.model;

public class Product implements java.lang.Cloneable,
                                java.io.Serializable
{
    public int id;

    public String name;

    public long price;

    public String desc;

    public Product()
    {
        this.name = "";
        this.desc = "";
    }

    public Product(int id, String name, long price, String desc)
    {
        this.id = id;
        this.name = name;
        this.price = price;
        this.desc = desc;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Product r = null;
        if(rhs instanceof Product)
        {
            r = (Product)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                return false;
            }
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.price != r.price)
            {
                return false;
            }
            if(this.desc != r.desc)
            {
                if(this.desc == null || r.desc == null || !this.desc.equals(r.desc))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::intf::model::Product");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, price);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, desc);
        return h_;
    }

    public Product clone()
    {
        Product c = null;
        try
        {
            c = (Product)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.id);
        ostr.writeString(this.name);
        ostr.writeLong(this.price);
        ostr.writeString(this.desc);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readInt();
        this.name = istr.readString();
        this.price = istr.readLong();
        this.desc = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Product v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Product ice_read(com.zeroc.Ice.InputStream istr)
    {
        Product v = new Product();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Product> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Product v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Product> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Product.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Product _nullMarshalValue = new Product();

    public static final long serialVersionUID = -1701094356L;
}
