// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `product.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.mycat.eshop.intf.service;

public interface ProductServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default com.mycat.eshop.intf.model.Product[] getProducts()
    {
        return getProducts(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default com.mycat.eshop.intf.model.Product[] getProducts(java.util.Map<String, String> context)
    {
        return _iceI_getProductsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<com.mycat.eshop.intf.model.Product[]> getProductsAsync()
    {
        return _iceI_getProductsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<com.mycat.eshop.intf.model.Product[]> getProductsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getProductsAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<com.mycat.eshop.intf.model.Product[]> _iceI_getProductsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<com.mycat.eshop.intf.model.Product[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getProducts", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     com.mycat.eshop.intf.model.Product[] ret;
                     ret = com.mycat.eshop.intf.model.ProductListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default com.mycat.eshop.intf.model.Product getProductById(int id)
    {
        return getProductById(id, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default com.mycat.eshop.intf.model.Product getProductById(int id, java.util.Map<String, String> context)
    {
        return _iceI_getProductByIdAsync(id, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<com.mycat.eshop.intf.model.Product> getProductByIdAsync(int id)
    {
        return _iceI_getProductByIdAsync(id, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<com.mycat.eshop.intf.model.Product> getProductByIdAsync(int id, java.util.Map<String, String> context)
    {
        return _iceI_getProductByIdAsync(id, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<com.mycat.eshop.intf.model.Product> _iceI_getProductByIdAsync(int iceP_id, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<com.mycat.eshop.intf.model.Product> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getProductById", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_id);
                 }, istr -> {
                     com.mycat.eshop.intf.model.Product ret;
                     ret = com.mycat.eshop.intf.model.Product.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ProductServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ProductServicePrx.class, _ProductServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ProductServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ProductServicePrx.class, _ProductServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ProductServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ProductServicePrx.class, _ProductServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ProductServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ProductServicePrx.class, _ProductServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ProductServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ProductServicePrx.class, _ProductServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ProductServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ProductServicePrx.class, _ProductServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ProductServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ProductServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ProductServicePrx ice_adapterId(String newAdapterId)
    {
        return (ProductServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ProductServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ProductServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ProductServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ProductServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ProductServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ProductServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ProductServicePrx ice_connectionCached(boolean newCache)
    {
        return (ProductServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ProductServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ProductServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ProductServicePrx ice_secure(boolean b)
    {
        return (ProductServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ProductServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ProductServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ProductServicePrx ice_preferSecure(boolean b)
    {
        return (ProductServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ProductServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ProductServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ProductServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ProductServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ProductServicePrx ice_collocationOptimized(boolean b)
    {
        return (ProductServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ProductServicePrx ice_twoway()
    {
        return (ProductServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ProductServicePrx ice_oneway()
    {
        return (ProductServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ProductServicePrx ice_batchOneway()
    {
        return (ProductServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ProductServicePrx ice_datagram()
    {
        return (ProductServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ProductServicePrx ice_batchDatagram()
    {
        return (ProductServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ProductServicePrx ice_compress(boolean co)
    {
        return (ProductServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ProductServicePrx ice_timeout(int t)
    {
        return (ProductServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ProductServicePrx ice_connectionId(String connectionId)
    {
        return (ProductServicePrx)_ice_connectionId(connectionId);
    }

    static String ice_staticId()
    {
        return "::intf::service::ProductService";
    }
}
